### ISSUE TITLE
Missing `DELETE /ddosx/v1/domains/{name}records/{id}`

### ISSUE THREAD

**Issue by phily245** [ukfast/cli#36]
The CLI tool is missing the command `ukfast ddosx domain record delete`.

The endpoint which it needs to hit is `DELETE /ddosx/v1/domains/{name}records/{id}` with no parameters and it should expect a response code of 204 on a successful deletion.

The documentation for this endpoint is at https://developers.ukfast.io/documentation/ddosx#/Record/delete_ddosx_v1_domains__name__records__id_

**Comment by 0x4c6565** [comment]
This command already exists:

```
ukfast safedns zone record delete --help
This command removes one or more zone records

Usage:
  ukfast safedns zone record delete <zone: name> <record: id>... [flags]
```

Are you mistaking this with a different command?
