### ISSUE TITLE
`--format/-f` flag update to `--output/-o`

### ISSUE THREAD

**Issue by 0x4c6565** [ukfast/cli#54]
This issue is discuss the possibility of changing the `--format/-f` flags to `--output/-o`, as I feel this is a better description of what this does.

**Comment by Overglazed** [comment]
Yeah I prefer --output/-o.  I think you also use --outputtemplate too for templates?

Depends whether you feel its necessary to maintain backwards compatibility or not.  Maybe  add a deprecate warning on -f  and then remove in next major version?
