### ISSUE TITLE
Allowing Custom Error Pages From A File

### ISSUE THREAD

**Issue by phily245** [ukfast/cli#57]
As in #45, custom error pages would make another location where it would be nice to upload a file, such as in DDoSX.

I see this as working nicely as both a post-deploy automation action for an application and making the tool more intuitive for a human user, as we have seen in after #45 was implemented.

**Comment by 0x4c6565** [comment]
Closed by https://github.com/ukfast/cli/pull/58

**Comment by 0x4c6565** [comment]
Included in release [v1.3.6](https://github.com/ukfast/cli/releases/tag/v1.3.6)
