### ISSUE TITLE
Discussion: Deletion confirmation

### ISSUE THREAD

**Issue by 0x4c6565** [ukfast/cli#91]
Discussion: should we add confirmation into `delete` commands, with a flag for bypassing the confirmation (such as `--force`)?

@Xiol @Overglazed @miff2000 @gavtaylor

**Comment by gavtaylor** [comment]
I'm not keen on flags like that, its just more to type and won't stop folk accidentally deleting something as they'd get into the habit of just adding the flag

had a look at a couple of other hosting providers cli tools and they don't have them

**Comment by miff2000** [comment]
A happy medium could be to use on only very destructive actions, like
deleting all domains, or maybe unrecoverable actions like deleting a VM

**Comment by gavtaylor** [comment]
are there any services you know of that support a flag like this?

just curious on the use case, we do this on web app side so makes sense to ask the question, but its not something I associate with terminal commands and I cant find any examples on ones I can think of that might have one, even on resources you'd want to be careful with like compute or data deletion, they just allow the call

a lot of tools flip it the other way and offer a `--dry-run` flag so you can test what *would* happen, so those that want that piece of mind can add the flag to test it, and those that live on the wild side can just run the command :)

**Comment by 0x4c6565** [comment]
> are there any services you know of that support a flag like this?
> 
> just curious on the use case, we do this on web app side so makes sense to ask the question, but its not something I associate with terminal commands and I cant find any examples on ones I can think of that might have one, even on resources you'd want to be careful with like compute or data deletion, they just allow the call
> 
> a lot of tools flip it the other way and offer a `--dry-run` flag so you can test what _would_ happen, so those that want that piece of mind can add the flag to test it, and those that live on the wild side can just run the command :)

Dry run is something I was thinking about instead too :)
